services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "TaskManagement"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmq:
  pgdata:
    driver: local